### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by stephan-gh** [msm8916-mainline/linux#20]
### Ready
See `SUBMITME:` commits in commit history :)

### Pending
TO BE UPDATED?

### Applied
- [x] [ASoC: qcom: apq8016_sbc: Fix oops with multiple DAI links](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=8201f11a1f75e3aa7d5327d0b1d8cb544aeaa62f) (5.3)
- [x] [dt-bindings: vendor-prefixes: Add Longcheer Technology Co., Ltd.](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=3af1e2aa1855d976337752c95ac0c4971d8fc9e6) (5.4)
  [dt-bindings: qcom: Document bindings for new MSM8916 devices](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=b72160fa886d757611b1c7f1127d5585fce43af2)
  [arm64: dts: qcom: Add device tree for Samsung Galaxy A3U/A5U](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=1329c1ab0730b521e6cd3051c56a2ff3d55f21e6)
  [arm64: dts: qcom: Add device tree for Longcheer L8150](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=16e8e8072108426029f0c16dff7fbe77fae3df8f)
- [x] [arm64: dts: msm8916-samsung-a2015: Enable WCNSS for WiFi and BT](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=efb9e0df7d8df9f6ccc4a02a52e56fb6e379e193) (5.5)
  [arm64: dts: msm8916-samsung-a5u: Override iris compatible](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=0d7051999175f97dfb1aa32e9008f08bf044a0a7)
- [x] ~~ASoC: msm8916-wcd-digital: Remove broken MIX2 DAPM routes~~, instead:
  [ASoC: msm8916-wcd-digital: add missing MIX2 path for RX1/2](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=bcab05880f9306e94531b0009c627421db110a74) (5.4)
- [x] [arm64: dts: msm8916-samsung-a2015: add tactile buttons and hall sensor](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=b1b8d080f72808f88bdb3dd3c9b69b115b052f5b) (5.5)
- [x] ~~extcon: sm5502: Clear pending interrupts during initialization~~, instead:
  [extcon: sm5502: Reset registers during initialization](https://git.kernel.org/pub/scm/linux/kernel/git/chanwoo/extcon.git/commit/?id=6942635032cfd3e003e980d2dfa4e6323a3ce145) (5.5)
- [x] [phy: qcom-usb-hs: Fix extcon double register after power cycle](https://git.kernel.org/pub/scm/linux/kernel/git/kishon/linux-phy.git/commit/?id=68eeb39a53d556f326101ed69a51e9a548f10971) (5.4)
- [x] [arm64: dts: msm8916-longcheer-l8150: Enable WCNSS for WiFi and BT](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=b0e1600dd46d305d6eac894bc3dd414321657e70) (5.5)
  [arm64: dts: msm8916-longcheer-l8150: Add Volume buttons](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=3ba8bbc41f5d1169c6a27de44df0d88d3a44f239)
- [x] [ASoC: msm8916-wcd-analog: Fix RX1 selection in RDAC2 MUX](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=9110d1b0e229cebb1ffce0c04db2b22beffd513d) (5.4)
  [ASoC: msm8916-wcd-analog: Add earpiece](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=7d2f70f248ab0e4251591cf7b36cc43281941f56) (5.5)
- [x] [drm/msm/dsi: Implement qcom, dsi-phy-regulator-ldo-mode for 28nm PHY](https://gitlab.freedesktop.org/drm/msm/commit/49c4868ab01cbe9bf06e23d5d65c8afea97ecf3f) (5.5)
- [x] [NFC: nxp-nci: Fix probing without ACPI](https://git.kernel.org/pub/scm/linux/kernel/git/davem/net.git/commit/?id=868afbaca1e2a7923e48b5e8c07be34660525db5) (5.5)
- [x] [arm64: dts: qcom: pm8916: Add vibration motor node](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=741a5ea7a69717ea1368ed98e431fbd6f5629a88) (5.6)
- [x] [iio: imu: st_lsm6dsx: Fix selection of ST_LSM6DS3_ID](https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?id=f8158000c5179371d0d146e7c4825718f9ffd80f) (5.5)
- [x] [drm/msm/dsi: Delay drm_panel_enable() until dsi_mgr_bridge_enable()](https://gitlab.freedesktop.org/drm/msm/commit/e5400750fafdaeee136e9fc3d1dde83d9251ee63) (5.6)
- [x] [ASoC: msm8916-wcd-analog: Fix selected events for MIC BIAS External1](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=e0beec88397b163c7c4ea6fcfb67e8e07a2671dc) (5.5)
- [x] [ASoC: msm8916-wcd-analog: Fix MIC BIAS Internal1](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=057efcf9faea4769cf1020677d93d040db9b23f3) (5.5)
- [x] [ASoC: msm8916-wcd-digital: Reset RX interpolation path after use](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=85578bbd642f65065039b1765ebe1a867d5435b0) (5.5)
- [x] [ASoC: msm8916-wcd-analog: Simplify MIC BIAS Internal](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=65fe457e7bafcbb844c66e8c54a414f090967eaa) (5.6)  
  [ASoC: msm8916-wcd-analog: Add MIC BIAS Internal3](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=00d852326e524214f046a5e1301eee84535a6863)
- [x] [Input: pm8xxx-vib - fix handling of separate enable register](https://git.kernel.org/pub/scm/linux/kernel/git/dtor/input.git/commit/?id=996d5d5f89a558a3608a46e73ccd1b99f1b1d058) (5.5)
- [x]  [arm64: dts: qcom: msm8916-samsung-a2015: Reserve Samsung firmware memory](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=8f4a7a00c1019df72cda3002643fb5823ef39183) (5.7)
- [x] [drm/modes: Make sure to parse valid rotation value from cmdline](https://cgit.freedesktop.org/drm/drm-misc/commit/?id=e6980a727154b793adb218fbc7b4d6af52a7e364) (5.6)
  [drm/modes: Allow DRM_MODE_ROTATE_0 when applying video mode parameters](https://cgit.freedesktop.org/drm/drm-misc/commit/?id=5c320b6ce7510653bce68cecf80cf5b2d67e907f)
- [x] [arm64: defconfig: Enable Qualcomm PM8XXX vibrator support](https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?id=33b8cd0065b4a6759dcc025c7f2fbd0a24858e6a) (5.7)
- [x] [ASoC: soc-pcm: fix regression in soc_new_pcm()](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=a4877a6fb2bd2e356a5eaacd86d6b6d69ff84e69) (5.7)
- [x] [media: venus: hfi_parser: Ignore HEVC encoding for V1](https://git.linuxtv.org/media_tree.git/commit/?id=c50cc6dc6c48300af63a6fbc71b647053c15fc80) (5.7)
- [x] [ASoC: qcom: q6asm-dai: Add SNDRV_PCM_INFO_BATCH flag](https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=7f2430cda819a9ecb1df5a0f3ef4f1c20db3f811) (5.7)
- [x] [dt-bindings: st_sensors: add st,lis2hh12 compatible entry](https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?id=09b2538d10dc542355877b2fe7c5cd3f7e237d66) (5.8)
  [iio: accel: st_sensors: add support for LIS2HH12](https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?h=testing&id=65c732f4b0315502bcefd88967bb871e5b85d0d0)
- TO BE UPDATED? (Many, many more!)

**Comment by antony-jr** [comment]
@Minecrell  I can only see your changes in ```for-next``` branch of ```git://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git``` should I submit my patches based on that branch too??

**Comment by Minecrell** [comment]
> @Minecrell I can only see your changes in `for-next` branch of `git://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git` should I submit my patches based on that branch too??

Yes.
