### ISSUE TITLE
kiwi: can't boot on KIW-AL00 3GB RAM

### ISSUE THREAD

**Issue by Boom-Hacker** [msm8916-mainline/linux#269]
i can't catch log,i only want to know do you support this device

**Comment by stephan-gh** [comment]
huawei-kiwi should be supported but we can't help without more information. Consider joining `#msm8939:matrix.org` on Matrix for device support, it's hard to help debug in GitHub issues.

**Comment by Boom-Hacker** [comment]
Can you tell about how to catch log in postmarket OS?I can't catch with android's way
