### ISSUE TITLE
kiwi: AUO OTM1901A panel can't work

### ISSUE THREAD

**Issue by Boom-Hacker** [msm8916-mainline/linux#274]
i added the panel drivers,but it still can't work

**Comment by stephan-gh** [comment]
As I wrote in your previous issue, please join [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) on Matrix (or `#msm8916-mainline` on OFTC IRC) for device porting help, it's hard to discuss such things in GitHub issues.
