### ISSUE TITLE
extcon: sm5502: platform 78d9000.usb: deferred probe pending

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8916-mainline/linux#283]
## Steps to reproduce

1. Install 6.1. USB works
2. Install 6.2-rc2 or later. `platform 78d9000.usb: deferred probe pending`
3. Downgrade the kernel to 6.1. USB works again

## Tested Devices
- samsung-a5
- samsung-e7
- samsung-grandmax
- samsung-j3
- samsung-j5 (not affected)
- samsung-j5x

**Comment by stephan-gh** [comment]
How can j5 not be affected? Isn't it the same setup as j5x?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Solved by adding rt5033/sm5703 regulator modules to `deviceinfo_modules_initfs`. They are not applied in msm8916-mainline, so this issue shouldn't happen on this repo.
