### ISSUE TITLE
Three cpu cores of wt88047 do not work.

### ISSUE THREAD

**Issue by wu17481748** [msm8916-mainline/linux#292]
[    0.002771] rcu:     Max phase no-delay instances is 1000.
[    0.004173] smp: Bringing up secondary CPUs ...                                      [    0.004711] psci: failed to boot CPU1 (-95)
[    0.004722] CPU1: failed to boot: -95
[    0.005300] psci: failed to boot CPU2 (-95)
[    0.005310] CPU2: failed to boot: -95
[    0.005857] psci: failed to boot CPU3 (-95)
[    0.005867] CPU3: failed to boot: -95
[    0.005916] smp: Brought up 1 node, 1 CPU
[    0.005926] SMP: Total of 1 processors activated.
[    0.005934] CPU features: detected: 32-bit EL0 Support
[    0.005939] CPU features: detected: 32-bit EL1 Support
[    0.005948] CPU features: detected: CRC32 instructions
[    0.006034] CPU: All CPU(s) started at EL1                                           [    0.006062] alternatives: applying system-wide alternatives
[    0.007807] devtmpfs: initialized
[    0.020915] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.020948] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.022148] pinctrl core: initialized pinctrl subsystem
[    0.023676] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.024947] DMA: preallocated 256 KiB GFP_KERNEL pool for atomic allocations
[    0.025161] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.025387] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.025444] audit: initializing netlink subsys (disabled)
[    0.026041] thermal_sys: Registered thermal governor 'step_wise'
[    0.026090] cpuidle: using governor menu
[    0.026220] NET: Registered PF_QIPCRTR protocol family
[    0.026390] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.026429] ASID allocator initialised with 65536 entries
[    0.032212] audit: type=2000 audit(0.024:1): state=initialized audit_enabled=0 res=1
[    0.040426] platform 1800000.clock-controller: Fixing up cyclic dependency with phy@1a98300 (1a00000.mdss)
[    0.049554] KASLR disabled due to lack of seed
[    0.050468] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.050482] HugeTLB: 16380 KiB vmemmap can be freed for a 1.00 GiB page
[    0.050491] HugeTLB: registered 32.0 MiB page size, pre-allocated 0 pages
[    0.050497] HugeTLB: 508 KiB vmemmap can be freed for a 32.0 MiB page
[    0.050505] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.050511] HugeTLB: 28 KiB vmemmap can be freed for a 2.00 MiB page                 [    0.050519] HugeTLB: registered 64.0 KiB page size, pre-allocated 0 pages
[    0.050525] HugeTLB: 0 KiB vmemmap can be freed for a 64.0 KiB page
[    0.051218] cryptd: max_cpu_qlen set to 1000
[    0.116446] raid6: neonx8   gen()  1386 MB/s
[    0.184541] raid6: neonx4   gen()  1438 MB/s
[    0.252654] raid6: neonx2   gen()  1383 MB/s
[    0.320754] raid6: neonx1   gen()  1186 MB/s
[    0.388861] raid6: int64x8  gen()   957 MB/s
[    0.456972] raid6: int64x4  gen()  1066 MB/s
[    0.525071] raid6: int64x2  gen()   933 MB/s
[    0.593203] raid6: int64x1  gen()   689 MB/s
[    0.593211] raid6: using algorithm neonx4 gen() 1438 MB/s
[    0.661279] raid6: .... xor() 1030 MB/s, rmw enabled
[    0.661287] raid6: using neon recovery algorithm
[    0.662095] iommu: Default domain type: Translated
[    0.662104] iommu: DMA domain TLB invalidation policy: strict mode
[    0.662396] SCSI subsystem initialized
[    0.662593] usbcore: registered new interface driver usbfs
[    0.662627] usbcore: registered new interface driver hub
[    0.662666] usbcore: registered new device driver usb
[    0.662872] pps_core: LinuxPPS API ver. 1 registered
[    0.662879] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.662901] PTP clock support registered
[    0.663125] CPUidle PSCI: Invalid PSCI power state 0x41000012
[    0.663135] dt-idle-genpd: failed to alloc PM domain /psci/power-domain-cluster
[    0.663150] CPUidle PSCI: failed to init PM domain ret=-12 /psci/power-domain-cluster
[    0.663176] CPUidle PSCI: failed to create CPU PM domains ret=-12
[    0.663183] psci-cpuidle-domain: probe of psci failed with error -12

**Comment by stephan-gh** [comment]
Make sure lk2nd is up to date
