### ISSUE TITLE
[discussion] qcom-msm8909-pins.dtsi

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8916-mainline/linux#294]
Should we also add `qcom-msm8909-pins.dtsi`, similar to `msm8916-pins.dtsi`?
And apply proper dt-schema on it, such as suffix `-state` and `-pins`.

**Comment by stephan-gh** [comment]
> Should we also add qcom-msm8909-pins.dtsi, similar to msm8916-pins.dtsi?

Having this separate isn't very popular upstream. :/

> And apply proper dt-schema on it, such as suffix -state and -pins.

Yes, definitely.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Link: https://lore.kernel.org/all/20230529-msm8916-pinctrl-v1-6-11f540b51c93@gerhold.net/
