### ISSUE TITLE
[Request] New release to at least 6.3-rc5

### ISSUE THREAD

**Issue by 185264646** [msm8916-mainline/linux#299]
The pmOS mainline support for uz801 needs a newer kernel.

**Comment by stephan-gh** [comment]
We can try to have a 6.3 release once that is out. Any help with testing is appreciated, I have pushed the `msm8916/6.3-rc6` branch - please report any problems you notice!

**Comment by 185264646** [comment]
> We can try to have a 6.3 release once that is out. Any help with testing is appreciated, I have pushed the `msm8916/6.3-rc6` branch - please report any problems you notice!

Thanks, I will have a test shortly.

**Comment by stephan-gh** [comment]
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/4031
