### ISSUE TITLE
Bootstrapping support for xiaomi-rolex

### ISSUE THREAD

**Issue by jmacato** [msm8916-mainline/linux#322]
I would like to know what kinds of things i should look out for if i want to test this mainline kernel source for 
https://wiki.postmarketos.org/wiki/Xiaomi_Redmi_4A_(xiaomi-rolex)

Right now it seems to be stuck with its original kernel and I hope i could help out with testing device tree configs etc etc.

**Comment by jmacato** [comment]
Sorry, i have mixed up msm8916 and msm8917

**Comment by stephan-gh** [comment]
@affenull2345 might be able to help you out with some msm8917 work.

**Comment by jmacato** [comment]
Do y'all have any discord/matrix servers i can join in?

**Comment by stephan-gh** [comment]
Sure, you can join [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) on Matrix. There is no Discord.
