### ISSUE TITLE
msm8916 wcn36xx Wi-Fi Monitor Mode

### ISSUE THREAD

**Issue by Ro-Den** [msm8916-mainline/linux#326]
`airmon-ng start wlan0`

`PHY     Interface       Driver          Chipset`

`phy0    wlan0           wcn36xx         Not pci, usb, or sdio`
**`                (monitor mode enabled)`**

But `airodump-ng -i wlan0` finds nothing.

https://github.com/KrasnikovEugene/wcn36xx/issues/94#issuecomment-21739675:
> So far monitor mode is not supported by FW.

It was 10 years ago and the repository is definitely abandoned.

Has anything changed? Is monitor mode possible nowadays?

**Comment by stephan-gh** [comment]
As far as I know nothing has changed. Monitor mode is still not supported. If it's not even supported by the proprietary firmware then there is not much we can do. Sorry.
