### ISSUE TITLE
dtsi downstreamed to kernel 6.1 ?

### ISSUE THREAD

**Issue by m01001101-01010110** [msm8916-mainline/linux#328]
Hello,

There is support for "msm8939.dtsi" in kernel v6.5 ( [https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/qcom?h=v6.5](url) ).

Kernel v6.1 being the LTS version, I'm wondering if the support for msm8939.dtsi will be downstreamed to it ?

Thank you.

**Comment by stephan-gh** [comment]
I think this question was answered in the chat. We focus on the latest mainline version. Eventually those changes will end up in the next LTS.
