### ISSUE TITLE
Unable to find xxxx.dtb in the following locations, I need help, 

### ISSUE THREAD

**Issue by kkv0id** [msm8916-mainline/linux#347]
I built with reference to this [document,](https://wiki.postmarketos.org/wiki/MSM8916_Mainlining) but it reported an error that dtb could not be found.
I haven't been able to resolve this error so I need help
My configuration related files:
APKBUILD:
```
pkgname=device-zhihe-ufi103s
pkgdesc="ZDX 4G LTE MiFi"
pkgver=1
pkgrel=0
url="https://postmarketos.org"
license="MIT"
arch="armv7"
options="!check !archcheck"
depends="
	postmarketos-base
	mkbootimg
	linux-postmarketos-qcom-msm8916
	soc-qcom-msm8916
"
makedepends="devicepkg-dev"
source="
	deviceinfo
	modules-initfs
"

build() {
	devicepkg_build $startdir $pkgname
}

package() {
	devicepkg_package $startdir $pkgname
}
```
deviceinfo:
```
# Reference: <https://postmarketos.org/deviceinfo>
# Please use double quotes only. You can source this file in shell
# scripts.

deviceinfo_format_version="0"
deviceinfo_name="ZDX 4G LTE MiFi"
deviceinfo_manufacturer="ZDX"
deviceinfo_codename="zhihe-ufi103s"
deviceinfo_year="2022"
deviceinfo_dtb="qcom/qcom-msm8916-zhihe-ufi103s"
deviceinfo_append_dtb="true"
deviceinfo_arch="armv7"
deviceinfo_screen_width="720"
deviceinfo_screen_height="1280"
deviceinfo_getty="ttyMSM0;115200"

# Device related
deviceinfo_chassis="embedded"
deviceinfo_keyboard="false"
deviceinfo_external_storage="false"

# Bootloader related
deviceinfo_flash_method="fastboot"
deviceinfo_kernel_cmdline="earlycon console=ttyMSM0,115200 PMOS_NO_OUTPUT_REDIRECT"
deviceinfo_generate_bootimg="true"
deviceinfo_bootimg_qcdt="false"
deviceinfo_bootimg_dtb_second="false"
deviceinfo_flash_pagesize="2048"
# deviceinfo_mtk_label_kernel=""
# deviceinfo_mtk_label_ramdisk=""
deviceinfo_flash_offset_base="0x80000000"
deviceinfo_flash_offset_kernel="0x00008000"
deviceinfo_flash_offset_ramdisk="0x01000000"
deviceinfo_flash_offset_second="0x00f00000"
deviceinfo_flash_offset_tags="0x00000100"
deviceinfo_flash_sparse="true"

```
[msm8916_defconfig.txt](https://github.com/msm8916-mainline/linux/files/14596424/msm8916_defconfig.txt)
I have added the dts file and fixed the makefile:
![image](https://github.com/msm8916-mainline/linux/assets/31177595/e3dd433e-01be-4046-81a0-2fefe1961b37)
![image](https://github.com/msm8916-mainline/linux/assets/31177595/78d694f2-d478-46db-990c-b21995422b73)
My command steps:
![image](https://github.com/msm8916-mainline/linux/assets/31177595/ff2d48c7-0246-4f4d-a374-94573efcadca)
pmbootstrap install error message:

![image](https://github.com/msm8916-mainline/linux/assets/31177595/c266e666-e8ed-45d8-9306-c21b1614347c)

**Comment by TravMurav** [comment]
Hi, by old convention 32bit arm platforms put all dtb files into the root of dtbs dir so you don't need leading `qcom/` dir in the path, this is what `qcom-` prefix in the file is for. However do you really need to build 32bit kernel for this device?

**Comment by kkv0id** [comment]
@TravMurav Thanks, I will try to remove qcom and rebuild. Yes, my hardware only supports 32 bit, I tried flashing its tz partition to support 64 bit, but that gave me quite a few weird problems that made me give up on 64 bit, so I tried building a 32 bit postmartkos

**Comment by kkv0id** [comment]
@TravMurav  Hello, the problem still exists. Thank you. I feel that the makefile of armv7 will not compile the dts file starting from 6.5.2. I will try 6.3.
![image](https://github.com/msm8916-mainline/linux/assets/31177595/9f10c98e-16f0-4116-9ef8-d32ba669d3bb)

**Comment by kkv0id** [comment]
add CONFIG_ARCH_QCOM=y in msm8916_defconfig

vi pmbootstrap/cache_git/pmaports/device/community/linux-postmarketos-qcom
-msm8916/APKBUILD  change /boot/dtbs to  /boot/dts
