### ISSUE TITLE
motorola-harpia: Properly implement display panel regulator

### ISSUE THREAD

**Issue by Sorixelle** [msm8916-mainline/linux#53]
harpia uses a NT50358 regulator to drive the display panel. This regulator is apparently compatible with the TPS65132, except for some differences with the enable lines, according to the downstream
kernel (https://github.com/MotorolaMobilityLLC/kernel-msm/blob/nougat-7.1.1-release-harpia/arch/arm/boot/dts/qcom/msm8916-harpia.dtsi#L202)

Currently, the regulator is just implemented as `regulator-fixed`, as the NT50358 has an onboard EEPROM it writes register values to, and loads from on startup. However, this is a bit of a hacky workaround, and we should figure out a proper way to drive the regulator. Downstream has a modified version of the TPS65132 driver with a flag in the device tree to enable the behaviour needed for the NT50358, but a better option might be to write a new driver similar to the TPS65132 specifically for the NT50358.

**Comment by Minecrell** [comment]
To be honest, it seems like this has worked just fine, even on other harpia devices. I don't think this is a real priority and there are plenty other things to do, so I think we can just close this. It seems like the oppo-a51f has a TPS65132 regulator as well and there they are using it as fixed-regulator even on downstream.
