### ISSUE TITLE
Move device nodes without memory resource from soc { ... } to / { ... }

### ISSUE THREAD

**Issue by lambdadroid** [msm8916-mainline/linux#9]
Similar to apq8016-sbc: https://github.com/torvalds/linux/blob/22051d9c4a57d3b4a8b5a7407efc80c71c7bfb16/arch/arm64/boot/dts/qcom/apq8016-sbc.dtsi#L499-L537

- [x] **a2015:** `i2c-muic`
- [x] **a2015:** `gpio-keys`, `gpio-hall-sensor`
- [x] **l8150:** `usb-id`

**Comment by TravMurav** [comment]
Cleanup commit is based on #11

**Comment by lambdadroid** [comment]
Done in 5.3 branch
